//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaContacto.Datos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Contacto
    {
        public int UserId { get; set; }
        [DisplayName("Primer Nombre:")]
        public string FirstName { get; set; }
        [DisplayName("Apellido:")]
        public string LastName { get; set; }
        [DisplayName("Correo Electrónico:")]
        public string Email { get; set; }
        [DisplayName("Teléfono:")]
        public string Mobile { get; set; }
    }
}
